$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    responsive:{
        0:{
            items:3
        },
        769:{
            items:5
        },
        1441:{
            items:10
        }
    }
})